version: '3'
services:
  myapp-main:
    image: golf-club-server:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_db
      - spring.datasource.password=password123
      - spring.datasource.username=root